### PR TITLE
[feature] restructured files and added check for 32bit

### PR DESCRIPTION
**Pull request by shaggytwodope**
This fully works for me, basiclly the script is 64bit mode.
However if it finds i386 is uname -m it'll remove the packages
steam and chrome from the listing. 

If possbile I'd like some testing before merging, as it is a 
rather considerable change from the current method. Altho the
code is really simple.

CC @Misko-2083 @linuxlite

### CODE REVIEW

**Comment by Misko-2083** [comment]
@shaggytwodope I like this. Quick installed everything on 32 bit. All good. Chrome and Steam are not on the list as expected.

**Comment by shaggytwodope** [comment]
@Misko-2083 great, when @linuxlite gets time to review I'll merge. I think this makes everything simpler for us, and we can have one version for both arch's. Thus being able to tag versions and maintain changelog alot easier. Just need to keep in mind going forward this is targeted at 64bit with 32bit rules. 

On a side note, we may need to double check teamviewer installs correctly? I just checked a diff between the old scripts and saw :i386 is ommited on 32bit one.

**Comment by Misko-2083** [comment]
@shaggytwodope Of course, t's easier to have just one.
I remember all the trouble with the teamviewer in the past.
Package naming was hell. Every single time there was a new version of teamviewer we had to change the scripts.  :smile: 
```bash
apt-cache showpkg teamviewer
Package: teamviewer
Versions: 
10.0.37742 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 33697fb60badd3f816da5b267ad1a01a


Reverse Depends: 
Dependencies: 
10.0.37742 - bash (2 3.0) libc6-i386 (2 2.4) lib32asound2 (0 (null)) lib32z1 (0 (null)) libxext6 (0 (null))
ia32-libs (0 (null)) ttf-liberation (16 (null)) fonts-liberation (0 (null))
 teamviewer5 (0 (null)) teamviewer5:i386 (0 (null)) teamviewer6 (0 (null)) teamviewer6:i386 (0 (null))
teamviewer7 (0 (null)) teamviewer7:i386 (0 (null)) teamviewer8 (0 (null)) teamviewer8:i386 (0 (null))
teamviewer9 (0 (null)) teamviewer9:i386 (0 (null)) teamviewer5 (0 (null)) teamviewer5:i386 (0 (null))
teamviewer6 (0 (null)) teamviewer6:i386 (0 (null)) teamviewer7 (0 (null)) teamviewer7:i386 (0 (null))
teamviewer8 (0 (null)) teamviewer8:i386 (0 (null)) teamviewer9 (0 (null)) teamviewer9:i386 (0 (null)) 
Provides: 
10.0.37742 - 
Reverse Provides: 
```

**Comment by linuxlite** [comment]
Will test this thoroughly early next week. Thanks folks.

**Pull request closed without merging**
