### PR TITLE
Consolidate Scripts into one.

### PR DESCRIPTION
**Pull request by gerito1**
Here is my proposal.
I merge all the install/remove functionality in one script for both architectures 64 and 32.
I've updated the progress bars detailing an approximated percentage of the installation but I could guess a way to set the speed.

This need heavy testing specially in the 32 branch but I suppose that there won't be mayor issues.
Also there is still redundancy in the code that could be improved.

### CODE REVIEW

**Comment by linuxlite** [comment]
Thank you for beginning work on the bounty. Currently getting this error when executing the main script: ./lite-software: line 600: syntax error: unexpected end of file

**Comment by gerito1** [comment]
Sorry I saw the error. The code was copied twice.
I was surprised because the code wasn't that long. Sometimes that happen me, I'm not very good with the notebook pad and when I do a double tap sometimes copy the text selected...
Sorry. Let's try again.

**Comment by linuxlite** [comment]
No problem, thanks for the fix. Tested installing and removing 3 applications, so initially the framework for combining packages work. Good luck with the next part (Replace the old progress bar on the installers with percentage and speed.) Thank you.

**Comment by Misko-2083** [comment]
Amazing job so far. Thanks for starting the work on bounty.
I've found a few issues:
¤ line 600: syntax error was showing untill I've changed the line 282 to this:
`--title="Lite-Software manager" --column="Choice" --column="Action" --column="Code Action" --hide-column=3 \`
¤ In line 43 `if [ "$(pidof synaptic gdebi-gtk)" ]; then` pidof will not find gdebi-gtk process ID, I would change that line to this `if [[ "$(pidof synaptic)"||"$(pgrep gdebi-gtk)" ]]; then`
¤ line 44 is not working properly because it will kill all synaptic and gdebi-gtk even if I click No. This will work:
`if zenity --question --ok-label="Yes" --cancel-label="No" --text="A package manager is still running. You want to close it?"; then`
For the progress bar percentage and data transfer rates maybe you can use pv.
http://blog.allanglesit.com/2011/08/bash-using-pv-to-display-progress-of-dd/
Good luck.

**Comment by gerito1** [comment]
Misko-2083 I really appreciate your input, thanks.

Ok I have bad news for you people.

Thanks for pointing me pv, but I don't know how apt-get does internally the download. The problem is that if is not exposed the pipe (which is merely a number, a file descriptor) I cannot access that information and without patching apt (if my guess is right) I won't be able to solve the problem as you want me to do.

I cannot rule out that possibility, but according to my knowledge (limited and perhaps wrong) pv won't work.

Second I had issues installing and downloading dropbox, and because it depends of external sources (and possibly flash also), the installations behaves quite differently as I expected so I need to fix that some way.

I've changed the installing and removing progress messages. Please I need feed back for that.

**Comment by linuxlite** [comment]
@gerito1 what problem did you experieince with Dropbox? It downloaded and installed here.

**Comment by gerito1** [comment]
@linuxlite nevermind.
I was stuck installing dropbox, and the installation never progressed. When I tried directly in apt-get in the console, usually got to 45% or 63%. But in my 8th try, I got it installed.

**Comment by linuxlite** [comment]
@gerito1 ok thank you. I'll put this through thorough testing over the next few days and let you now how I get on. Thank you for your commits to date.

**Comment by Misko-2083** [comment]
You are right about mv. It will not work.
I've had a few ideas. Maybe you can use them:
http://pastebin.com/SXccgNPK
Tested dropbox and it's working but takes a lot of time to install and dowload and there is no progress bar.
You can try this: remove dropbox, then `sudo apt-get clean` and then run this:
`stdbuf -oL -eL sudo apt-get install -y nautilus-dropbox --show-progress |  stdbuf -oL sed -n -e 's/Progress:[ ]\[//;s/%\]//;s/^[ \t]*//p' -e 's/^/#/p' | zenity --progress --auto-close`
I will do some testing on the work you have done so far. Thank you.

**Comment by linuxlite** [comment]
@gerito1 see if you can replicate this issue. Install LL 2.2 32bit in a virtual machine or on a test pc (assuming you haven't already) run: gksudo lite-software and select to install everything in the list. After everything is downloaded we lose the dialogue box for a long time until everything has finished installing. If I select 2 or 3 items to install, the dialogue boxes appear normally. So this seems to happen when a large amount of software is selected.

**Comment by linuxlite** [comment]
@gerito1 Deluge, Skype and Totem remain installed upon removal. This is because they all have different names when uninstalling. Deluge - deluge-gtk, Skype - skype-bin, Totem - totem (gets installed when you install 'Apple Trailers Plugin') Suggest adding apt-get autoremove to the removal process to clean up packages. Adding apt-get autoremove should remove Deluge and Skype completely. I have made some minor changes to code and wording, can you use this code please from this point on - https://gist.github.com/linuxlite/5ee4ab522f6bd9f32db5 Thank you.

**Comment by linuxlite** [comment]
@gerito1 can you also please remove the desktop notification that appears from libnotify. The zenity notification is sufficient. Once we have fixed all the bugs and have it all working perfectly I would like to give you the bounty. Thanks you.

**Comment by Misko-2083** [comment]
@linuxlite Jerry, if we change line 120 to
`if [ "${TEST_PKG[1||2||3||4||5]}" == "(none)" ];then`
Then if any package is missing(for example one game from the Games Pack), the line in a list will be marked as 'Not Installed'
then we can add skype-bin, totem and deluge-gtk to the list. No need to add autoremove.

Line 90:
`appletrailers=("FALSE" "Apple Trailers Plugin" "Internet" "" "Watch Apple trailers in your web browser (Firefox only)" "totem-mozilla ubuntu-restricted-extras totem" "" )`
line 106:
`skype=("FALSE" "Skype" "Internet" "" "A popular audio and video chat application" "skype skype-bin" "" )`
And line 108:
`torrent=("FALSE" "Torrent Software" "Internet" "" "Installs the Deluge Torrent client software" "deluge deluge-gtk" "" )`

I've installed everything and I haven't noticed that the progress dialog was missing.

@gerito1 can you add 'exit' at the end of the script. Also when no package is installed I can open the 'remove' dialog list and there is an empty box there. If I select the box and then click on 'Remove' It will output an error. Is there a way not to display the Remove dialog list when no package is installed? Instead of that there could be one info dialog that says: No package/application is installed.

**Comment by linuxlite** [comment]
@Misko-2083 did you select all of the software in the list at once, then click on Install? Or did you install everything one at a time?

**Comment by gerito1** [comment]
@linuxlite @Misko-2083 I could reproduce the issue. Installing all the software at once in a clean set-up, close immediately the second dialog of the installation (the one that show apt configuring the software).
Probably awk is printing a 100% and thus closing it. It's late and I have to go to the bed.
Thanks for the feedback I would look into, later.

**Comment by linuxlite** [comment]
Fresh Linux Lite 2.2 install on hardware, 64bit. I do all the updates first. Then run Lite Software, select all software to install, fails with message 'Error The package(s) could not be installed'.

**Comment by linuxlite** [comment]
Re. 64bit test, in the current lite software, the following app is different: 'teamviewer:i386' in 32bit it is 'teamviewer' if this helps.

**Comment by gerito1** [comment]
@linuxlite About the dialog, I've just fixed that. Thanks, I never saw that error before.

@Misko-2083 @linuxlite About the packages. deluge and others have a transitional package. Those  are empty, and are optional. In that case we must to find those packages that are fundamental to all, for example deluge-common.

If you can see how is composed the list of packages, the last two are the "main" packages and the "optional" packages. In the case of deluge we should put something like "deluge-common" "deluge" or something like that.

@Misko-2083  The script check for every package in the main list the "element[5]" (or list of main packages) but ignores optional packages the "element[6]". I did that way to avoid delete packages like "libavformat-extra-54" used by other packages. There's no need to change that.
In  the case of the game pack, if one game is not installed, the script consider that the pack is not installed. But for example the video pack is installed if openshot and blender are installed, independently if libavformat-extra-54 it is.

But if there are orphan packages, probably @linuxlite might be right.

**Comment by gerito1** [comment]
@linuxlite I'm leaving 'teamviewer:i386' as it is because otherwise it fails to install, for some odd reason.
It is 32bit, that way is installed with multilib (I think).
If you are comparing the scripts use meld to see the additions, deletions, modifications side by side.
Both are the same scripts but with different "packages".

**Comment by linuxlite** [comment]
@gerito1 feedback on latest commit. With everything selected to be installed. We've lost the progress dialogue, now it just sits on this window with no progress:

then goes to the next step. It does download, theres just no indication.
During the unpacking process of the debs, the installer gets stuck on here:

**Comment by linuxlite** [comment]
@gerito1 feedback on latest 64bit commit. Download progress works fine.
At the end of downloading the packages, we get this:

**Comment by gerito1** [comment]
@linuxlite about your last message. It says Kodi is not found. In 64. It's a problem with the repo.
@linuxlite Give me a while and I will fix the previous error.

**Comment by gerito1** [comment]
@linuxlite To fix the last problem you reported, we should keep a log.
Here is the log https://gist.github.com/gerito1/55f6f7b3882743e1b73a
See that there are missing packages, apt-get update will fix this.

**Comment by linuxlite** [comment]
At the beginning of the script, there is "Check if apt-cache was built and ask for update if needed" but I have never seen this pop up.

**Comment by gerito1** [comment]
@linuxlite It does, the first time it runs.

**Comment by gerito1** [comment]
@linuxlite Sorry, I accidentalli closed the pull request

**Comment by linuxlite** [comment]
@gerito1 on the 64bit when I ran the script I never got the pop up, even though I did need updates. Same with the 32bit.

**Comment by linuxlite** [comment]
At some stage this week, I'm going to do fresh clean installs on both arch's and run the script after first boot.

**Comment by gerito1** [comment]
@linuxlite Ok. I will improve the error messages for both, install and remove.
I will create log files for apt-get output.
Also, decide if we need or not to run apt-get autoremove. And in which circounstances.

**Comment by linuxlite** [comment]
@gerito1 sounds good :) I think that the scripts should log all activity to eg. /var/log/litesoftware.log perhaps we could have this feature instead of speed readout as specified in the Bounty. What do you think?

**Comment by gerito1** [comment]
@linuxlite The speed is out of my reach, simple as that. I would need to access to information internal to apt-get.
The log is more accesible.

**Comment by linuxlite** [comment]
Sounds good, I'm happy with that.

**Comment by linuxlite** [comment]
I've updated the Bounty to...

"We're looking for a developer to add a number of new features to Lite Software.

1) If a user selects multiple programs to install, the installer will no longer run each script individually, all of their choices will be combined into one.
2) Log all output to /var/log/lite-software.log"

**Comment by gerito1** [comment]
@linuxlite I ran again the script in a clean environment.
About this #Check if apt-cache was built and ask for update if needed
It runs only once to build the cache of packages. That's a behavior I did never modified from the original script.
We could enforce that dialog once per boot making a temporal file in /tmp for example.
But perhaps that would be very intrusive.

**Comment by linuxlite** [comment]
@gerito1 there is a gap in the loading of Lite Software where people would wonder 'this app is slow, or something is wrong, it's not loading' I would like this dialogue to appear each time just to let them know what is happening, especially helpful for slower computers. Thank you.

**Comment by gerito1** [comment]
@linuxlite Sorry for the delay. Some problems in the way.
About "gaps" please be more specific.

In the installation, I have the problem that I'm using awk, so I'm waiting for an "\n" for process every input (a line in this case).

As you might know, the percentage in the input it's not captured because that. If I handle differently the complexity would kill me and it's a problem. So until I have no input, I'm stuck.

Dropbox it's a problem by it's own. Dropbox fails frequently, not the downloading but the configuration part. It consist in 2 parts, the first one is download files from external repos (and again I don't get the "\n"), then the unpacking and that part always go smoothly, but the downloading fails often.

Ok now, I need to solve the actualization of the repository info (the prepare part).
I don't know. We could enforce the apt-get update one per boot... it's a little tedious, but we won't fail as often the installation part. If the database is up to date, takes seconds to a minute.

**Comment by linuxlite** [comment]
@gerito1 Gaps - a period of time where there is no information for the user. User launches lite-software, the 'Choose a task' window appears, user selects either Install software of Remove software, then there is a gap or waiting period before the main window appears. We should have a dialogue saying something like, 'Please wait, loading Install Software' or similar.

**Comment by linuxlite** [comment]
@gerito1 regarding 'We could enforce the apt-get update one per boot' we won't do that.

**Comment by linuxlite** [comment]
@gerito1 regarding 'We could enforce the apt-get update one per boot' we won't do that. Lets replace the '#Check if apt-cache was built and ask for update if needed' section with:

```
# Update system packages
zenity --question --title="Package Updater" --window-icon="/usr/share/icons/zenity-llcc.png" --text="We will now fetch the Updates list.\n\nClick Yes to continue or No to abort."
   if [ "$?" -eq "0" ];then

x=$( stdbuf -oL /bin/bash \-c '(sudo apt-get update \-y )' 2>&1 |
stdbuf -oL sed -n -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p'|
zenity --progress --title="Updating package information..." --pulsate \
--width=600 --auto-close )
```

and make this a part of Lite Software. This should run only once at the start up of Lite Software. Once the update is done, the main Lite Software window is loaded. Failure is not an option :thumbsup:

**Comment by gerito1** [comment]
@linuxlite Ok, that iteration was longer than I expected.
Now the problem "filling" the list should be almost gone. It was pretty difficult for me wrap this one, but now I think that I did it.
Ok, there's much going on before we show the list of software, so there will be a delay, but now the list are filled almost instantly.

**Comment by linuxlite** [comment]
@gerito1 Thanks. I've been doing a lot of testing on an older laptop. I'm going to see how this runs on a 'modern' pc and let you know the results. Hopefully we can wrap this up soon, and have it ready for LL 2.4 in April.

**Comment by linuxlite** [comment]
Issue closed @gerito1 please claim the Bounty.

**Comment by gerito1** [comment]
Oh. That's a surprise. Thanks.
I will do.
If there's other problem/issue I will be watching.

**Comment by linuxlite** [comment]
Thank you @gerito1 I wanted to merge this into the master so that we can continue collaboration there and you've done a lot of work on this and I thought you were due just rewards. I'll make some cosmetic changes to the code soon and update the master. So from now on please pull from there. Thank you again :smiley:

**Comment by gerito1** [comment]
@linuxlite Well yeah sure. I did it for the money.
That's doesn't mean that I do not want to help.
I'm a contributor for other open source projects, so it's nice to help.
Thank you.

**Pull request merged**
