### PR TITLE
Small notification touch

### PR DESCRIPTION
**Pull request by ralphys**
A little notification touch - After checking for updates with Lite Install Updates and finding new updates but cancelling instead of updating... this notification will be displayed.

### CODE REVIEW

**Comment by linuxlite** [comment]
I have a test several times, not getting the notification, still getting the old one. Click on OK on the old notification and the mouse wheel spins for a few seconds, then mouse returns to normal. See video demo in attachment.


[upd.zip](https://github.com/linuxlite/litesoftware/files/623743/upd.zip)

**Comment by ralphys** [comment]
I'm pretty sure you are not running the latest commits because your video doesn't show th correct cancelled window comment. I have tested the code in 32 and 64 bits and works as expected, plus the dialogs look completely different.

**Comment by linuxlite** [comment]
Does this look right to you? - https://raw.githubusercontent.com/linuxlite/litesoftware/master/32/usr/scripts/updates-gui

**Comment by ralphys** [comment]
No it does not. And looking at my own fork it doesn't seem that the files I pushed are there. This is quite odd! I'm 100% convinced I uploaded the latest updates... Let me send you another pull :/

Quite strange regardless!

**Comment by linuxlite** [comment]
Not a problem Ralphy :)

**Comment by ralphys** [comment]
Check the latest commit pull :)

**Comment by linuxlite** [comment]
Now it's getting a little messy. I used the cli instructions suggested by Github and it messed up (thanks Github). Can you please submit a normal merge request with your recent changes the way we have up until now. Thank you.

**Comment by ralphys** [comment]
I did... I have a normal merge request open and the code seems ok in that request I sent. Do you want me to cancel it and create a new one?

**Comment by linuxlite** [comment]
Yes please Ralphy.

**Comment by ralphys** [comment]
Done, check again please.

**Pull request merged**
